# Generated by Django 5.1.7 on 2025-03-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='car',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='track',
        ),
    ]
