# Generated by Django 5.1.7 on 2025-03-19 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_track_avg_lap_time_minute_track_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_date',
            field=models.DateTimeField(default='2024-06-01T12:00:00Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.track'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'booked_date')},
        ),
    ]
