# Generated by Django 5.1.7 on 2025-04-09 10:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_booking_booked_date_booking_car_booking_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_asset_path',
            field=models.CharField(default='/static/images/default.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
    ]
