# Generated by Django 5.2 on 2025-05-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_car_image_asset_path_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='number_of_turns',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
